from unicodedata import name
import joblib
import streamlit as st
import pandas as pd
from PIL import Image
from numpy import nan 

model_file = 'car_auction_rf.joblib'
preprocessor_file = 'car_auction_preprocessor.joblib'

rf_model = joblib.load(model_file)
rf_model = rf_model['model']
data_preprocessor = joblib.load(preprocessor_file)

def extract_year(df):
  df['Date'] = pd.to_datetime(df.PurchDate)
  df['PurchaseYear'] = df.Date.dt.year
  df['PurchaseMonth'] = df.Date.dt.month
  df['PurchaseDay'] = df.Date.dt.day
  return df

def predict_input(model, single_input):
    numeric_cols, encoded_cols = data_preprocessor['numeric_cols'], data_preprocessor['encoded_cols']
    categorical_cols = data_preprocessor['categorical_cols']
    input_df = pd.DataFrame(single_input)
    input_df = extract_year(input_df)
    input_df[numeric_cols] = data_preprocessor['imputer'].transform(input_df[numeric_cols])
    input_df[numeric_cols] = data_preprocessor['scaler'].transform(input_df[numeric_cols])

    input_df[encoded_cols] = data_preprocessor['encoder'].transform(input_df[categorical_cols].values)
    return rf_model.predict(input_df[numeric_cols + encoded_cols])

def main():
    banner_img = Image.open('./images/banner.jpg')
    logo_img = Image.open('./images/auction_logo.png')

    st.image(banner_img)

    st.sidebar.info(body='Car Auction Good/Bad Buy')
    add_selectbox = st.sidebar.selectbox('How would you like to predict ?', ('Online', 'Batch'))
    st.sidebar.info('This app is created to predict if your will get kicked in auction or not !')
    st.sidebar.image(logo_img)
    st.title('Dont Get Kicked')
    try:
        if add_selectbox == 'Online':
            aucguart = st.selectbox('Auction',['Red','Green'])
            auction = st.selectbox('Auction',['MANHEIM','ADESA','Other'])
            byrno = st.number_input('Buyer Number',min_value=800,max_value=99000)
            color = st.selectbox('Color',['RED', 'WHITE', 'MAROON', 'SILVER', 'BLACK', 'GOLD', 'GREY',
        'BLUE', 'BEIGE', 'PURPLE', 'ORANGE', 'GREEN', 'BROWN', 'YELLOW',
        'NOT AVAIL', 'OTHER'])
            onlinesale =  st.selectbox('Is Online Sale ?',[0,1])
            model=  st.selectbox('Vehicle Model',['MAZDA3',
        '1500 RAM PICKUP 2WD',
        'STRATUS V6',
        'NEON',
        'FOCUS',
        'GALANT 4C',
        'SPECTRA',
        'TAURUS',
        'FIVE HUNDRED',
        '1500 SIERRA PICKUP 2',
        'F150 PICKUP 2WD V6',
        'CARAVAN GRAND FWD V6',
        'ALTIMA',
        'CAVALIER 4C',
        'TRAILBLAZER 2WD 6C',
        'VUE 2WD 4C',
        'IMPALA',
        'ENVOY XL 2WD 6C',
        'VOYAGER FWD V6',
        'MONTE CARLO',
        'VENTURE FWD V6',
        'HHR',
        'SABLE',
        'ENVOY XL 4WD 6C',
        'DURANGO 4WD V8',
        'SUBURBAN 1500 2WD',
        'EXPLORER 2WD V6',
        '300',
        'MUSTANG V6',
        'AVALANCHE 1500 2WD V',
        'WINDSTAR FWD V6',
        'FREESTAR FWD V6',
        'SONATA V6',
        'CALIBER',
        'SENTRA',
        'PACIFICA FWD',
        'IMPALA V6',
        'XTERRA 2WD V6',
        'COROLLA',
        'G6 V6',
        'ION',
        'DURANGO 2WD V8',
        'FUSION 4C',
        '4 RUNNER 2WD V8',
        'GRAND PRIX',
        'SEBRING V6',
        'FORENZA',
        'MAZDA5',
        'LIBERTY 2WD V6',
        'DAKOTA PICKUP 2WD V6',
        'TAHOE 2WD',
        'COBALT',
        'EXPEDITION 2WD V8',
        'ELEMENT 2WD',
        'SUNFIRE',
        'RELAY 2WD V6',
        'FREESTYLE 2WD V6',
        'F150 PICKUP 2WD V8',
        'TRAILBLAZER EXT 2WD',
        'PT CRUISER',
        'TRACKER 2WD V6',
        'DURANGO 2WD V6',
        'MALIBU V6',
        'ALERO 4C',
        'TOWN & COUNTRY FWD V',
        'CAMRY V6',
        'MAGNUM V6',
        'EQUINOX FWD V6',
        'STRATUS 4C',
        'LIBERTY 2WD 4C',
        'MAZDA6',
        'CAMRY 4C',
        'FREESTYLE FWD V6',
        'L SERIES',
        'RENO',
        'SEBRING 4C',
        'SILHOUETTE',
        'ESCAPE 4WD V6',
        'OPTIMA 4C',
        'RANGER PICKUP 2WD V6',
        'G6 4C',
        'ENVOY 2WD 6C',
        'ACCENT',
        'UPLANDER FWD V6',
        'ELANTRA',
        '1500 SILVERADO PICKU',
        'PARK AVENUE',
        'ENDEAVOR FWD',
        'AMANTI',
        'TUCSON 2WD 4C',
        'XB',
        'EXPLORER 4WD V6',
        'ESCAPE 2WD V6',
        'CARAVAN FWD V6',
        'TRIBUTE 2WD 4C',
        'SONATA 4C',
        'RENDEZVOUS FWD',
        'ACCORD 4C',
        'ESCAPE 2WD 4C',
        'MALIBU max_valueX V6',
        'COLORADO PICKUP 2WD',
        'REGAL',
        'SANTA FE 2WD V6',
        'GRAND CHEROKEE 2WD V',
        'MALIBU 4C',
        'AVEO',
        'CHARGER V6',
        'AVENGER 4C',
        'RIO',
        'PATRIOT 4WD 4C',
        'SORENTO 4WD',
        'JOURNEY FWD 4C',
        'AURA',
        'AVENGER V6',
        'TRIBUTE 2WD V6',
        'F150 PICKUP 4WD V8',
        'FUSION V6',
        'TERRAZA FWD V6',
        'ENDEAVOR AWD',
        'VIBE',
        'TOWN & COUNTRY 2WD V',
        'CHARGER',
        'VERSA',
        'JETTA 5C',
        'SABLE 3.0L V6 EFI',
        'PACIFICA FWD 3.5L V6',
        'IMPALA 3.5L V6 SFI',
        'COBALT 2.2L I4 MPI',
        'SORENTO 4WD 3.5L V6',
        'UPLANDER FWD V6 3.9L',
        'VENTURE AWD V6',
        'EXPEDITION 4WD V8 5.',
        'TRACKER 4WD V6 2.5L',
        'MALIBU V6 3.5L V6 SF',
        'MUSTANG V6 4.0L V6 E',
        'LIBERTY 4WD V6 3.7L',
        'BRAVADA AWD V6 4.2L',
        'IMPALA 3.4L V6 SFI',
        'CHARGER V6 2.7L V6 M',
        'TAURUS 3.0L V6 EFI S',
        '300 2.7L V6 MPI',
        'MONTE CARLO 3.5L V6',
        'MAGNUM V6 2.7L V6 MP',
        'ION 2.2L I4 EFI / SF',
        'AVEO 1.6L I4 EFI',
        'SEBRING 4C 2.4L I4 E',
        'MALIBU 4C 2.2L I4 MP',
        'FIVE HUNDRED 3.0L V6',
        'MALIBU max_valueX V6 3.5L',
        'SEBRING 4C 2.4L I4 S',
        'SONATA V6 2.7L V6 MP',
        'ELANTRA 2.0L I4 MPI',
        'MARINER 2WD V6 3.0L',
        'SEBRING V6 2.7L V6 M',
        'TRAILBLAZER 4WD 6C 4',
        'PT CRUISER 2.4L I4 M',
        'ELANTRA MFI I-4 2.0L',
        'CAVALIER 4C 2.2L I4',
        'ASCENDER 2WD 6C 4.2L',
        'ALTIMA 2.5L I4 MPI',
        'HHR 2.2L I4 MPI',
        'STRATUS 4C 2.4L I4 S',
        'GRAND PRIX 3.8L V6 S',
        'PT CRUISER 2.4L I4 S',
        'STRATUS 4C 2.4L I4 M',
        'PT CRUISER 2.4L I-4',
        'SANTA FE 4WD V6 2.7L',
        'ECLIPSE',
        'GRAND AM V6 3.4L V6',
        'SONATA V6 3.3L V6 MP',
        'BONNEVILLE 3.8L V6 S',
        'EQUINOX AWD V6 3.4L',
        'FORENZA 2.0L I4 EFI',
        'CONCORDE 3.5L V6 MPI',
        'ION 2.2L I4 EFI',
        'VENTURE FWD V6 3.4L',
        'ION 2.0L I4 MPI',
        'SENTRA 2.5L I-4 EFI',
        'TAHOE 4WD 4.8L V8 SF',
        'SPORTAGE 2WD 4C 2.0L',
        'DURANGO 4WD V8 5.7L',
        'MALIBU V6 3.1L V6 SF',
        'WINDSTAR FWD V6 3.8L',
        'ALTIMA 3.5L V6 MPI',
        'PACIFICA AWD 3.5L V6',
        'SONATA 4C 2.4L I4 MP',
        'VIBE 1.8L I4 MPI',
        'MAZDA6 2.3L I4 MFI /',
        'EXPLORER 4WD V6 4.0L',
        'FOCUS 2.0L I-4 EFI D',
        'ACCORD V6 3.0L V6 EF',
        'ESCAPE 2WD V6 3.0L V',
        'VUE AWD 4C 2.2L I4 M',
        'RENDEZVOUS FWD 3.4L',
        'ACCENT 1.6L I4 MPI',
        'TOWN CAR 4.6L V8 EFI',
        'OPTIMA 4C 2.4L I4 MP',
        'FOCUS 2.0L I4 SFI',
        'MONTE CARLO 3.4L V6',
        'FREESTYLE 2WD V6 3.0',
        'MILAN V6',
        'LIBERTY 4WD V6',
        'CARAVAN FWD 4C',
        'XL-7 4WD',
        'FREESTYLE AWD V6',
        'GRAND AM V6',
        'S SERIES',
        'PACIFICA AWD',
        'EQUINOX AWD V6',
        'HIGHLANDER 2WD V6',
        'TRAILBLAZER EXT 4WD',
        'LANCER',
        'max_valueIMA',
        'EXPEDITION 4WD V8',
        'COOPER',
        'ACCORD V6',
        'GRAND AM 4C',
        'MILAN 4C',
        'ENVOY 4WD 6C',
        'RENDEZVOUS AWD',
        'CENTURY V6',
        'TRAILBLAZER 4WD 6C',
        'TRIBUTE 4WD V6',
        'MONTEGO',
        'S10 PICKUP 2WD 4C',
        'GRAND CHEROKEE 4WD V',
        '1500 RAM PICKUP 4WD',
        'TORRENT FWD V6',
        'AVALANCHE 1500 4WD V',
        'EXPLORER 2WD V8',
        'TAHOE 4WD',
        'GALANT V6',
        'NEON 2.0L I-4 SFI SO',
        'TAURUS 3.0L V6 EFI',
        'SPECTRA 2.0L I4 EFI',
        'PACIFICA FWD 3.8L V6',
        'CHARGER V6 3.5L V6 E',
        'CAMRY SOLARA V6 3.0L',
        'RIO 1.6L I4 MPI',
        'CIVIC',
        'TRAILBLAZER 2WD 6C 4',
        'MAGNUM V6 3.5L V6 MP',
        'CHARGER 3.5L V6 EFI',
        'LACROSSE 3.8L V6 SFI',
        'G6 4C 2.4L I4 MPI',
        'IMPALA V6 3.5L V6 SF',
        'MUSTANG V6 3.8L V6 E',
        'G6 V6 3.5L V6 SFI',
        'RENO 2.0L I4 EFI',
        'CARAVAN FWD 4C 2.4L',
        'ACCORD 4C 2.4L I4 MP',
        'EXPLORER 2WD V6 4.0L',
        'ALTIMA 2.5L I-4 EFI',
        'max_valueIMA MFI V6 3.5L D',
        '300 3.5L V6 MPI',
        'ECLIPSE 2.4L I4 MPI',
        'TAURUS 3.0L V6 EFI /',
        'LIBERTY 2WD V6 3.7L',
        'CHARGER 2.7L V6 MPI',
        'MILAN V6 3.0L V6 EFI',
        'FIREBIRD V6 3.8L V6',
        'PATRIOT 2WD 4C',
        'RONDO V6',
        'FORESTER AWD',
        'XTERRA 2WD 4C',
        'DAKOTA PICKUP 2WD V8',
        'TIBURON',
        'CAMRY SOLARA V6',
        'MONTANA',
        'NITRO 2WD V6',
        'YARIS',
        'G5 4C',
        'AURA V6',
        'RANGER PICKUP 2WD 4C',
        'SPORTAGE 2WD 4C',
        'MOUNTAINEER 2WD V6',
        'CROWN VICTORIA',
        'ALERO V6',
        '300M',
        'GRAND CHEROKEE 4WD 6',
        'LE SABRE',
        'MATRIX 2WD',
        'VOYAGER FWD 4C',
        'SENTRA 1.8L I4 EFI',
        'ENVOY 2WD 6C 4.2L I-',
        'F150 PICKUP 2WD V8 5',
        'ION 2.2L I4 MPI',
        'FREESTAR FWD V6 3.9L',
        'MONTANA FWD 3.4L V6',
        'ALERO V6 3.4L V6 MPI',
        'COBALT 2.2L I4 MPI /',
        'UPLANDER FWD V6 3.5L',
        'VUE 2WD 4C 2.2L I4 M',
        'GRAND VITARA 2WD 2.5',
        'AVEO 1.6L I-4 EFI DO',
        'MOUNTAINEER AWD V6 4',
        'XL-7 2WD 3.6L V6 EFI',
        'DURANGO 2WD V8 4.7L',
        'AVEO 1.6L I4 EFI / M',
        'ACCORD 4C 2.4L I-4 M',
        'CALIBER 2.0L I4 SFI',
        'TAHOE 2WD 4.8L V8 SF',
        'F150 PICKUP 2WD V8 4',
        'SORENTO 2WD 3.5L V6',
        'EQUINOX FWD V6 3.4L',
        'MALIBU 4C 2.2L I4 MF',
        'ENVOY 2WD 6C 4.2L I6',
        'TITAN PICKUP 2WD V8',
        'GRAND AM 4C 2.2L I4',
        'ALTIMA 2.5L I4 MPI /',
        'AVENGER 4C 2.4L I4 S',
        'IMPALA 3.9L V6 SFI',
        'HHR 2.4L I-4 MPI',
        'MONTANA FWD 3.5L V6',
        'max_valueIMA 3.5L V6 MPI',
        'CENTURY V6 3.1L V6 S',
        'FUSION 4C 2.3L I4 EF',
        'RONDO V6 2.7L V6 DI',
        'FREESTYLE FWD V6 3.0',
        'DURANGO 4WD V8 4.7L',
        'IMPALA V6 3.5L V6 MP',
        'IMPALA 3.8L V6 SFI',
        'LACROSSE',
        'TUNDRA PICKUP 2WD V8',
        'MARINER 2WD V6',
        'GRAND MARQUIS',
        'AURA 4C',
        'MARINER 4WD V6',
        'EXPLORER AWD V6',
        'BEETLE',
        'VUE 2WD V6',
        'YUKON XL 1500 4WD',
        'SONATA 4C MFI I-4 2.',
        'SANTA FE 2WD V6 2.7L',
        'NEON 2.0L I4 SFI',
        'XG 350 3.5L V6 EFI /',
        'TRACKER 2WD 4C 2.0L',
        'GRAND CHEROKEE 2WD 6',
        'LANCER 2.0L I4 MPI',
        'MUSTANG V6 3.9L V6 E',
        'SABLE 3.0L V6 EFI DO',
        'LE SABRE 3.8L V6 MFI',
        'SPORTAGE 2WD Multipl',
        'FREESTYLE AWD V6 3.0',
        'ESCAPE 4WD V6 3.0L V',
        'XTERRA 2WD V6 3.3L V',
        'ELEMENT 2WD 2.4L I4',
        'EXPEDITION 2WD V8 5.',
        'SPECTRA 1.8L I4 EFI',
        'OPTIMA V6',
        'VUE AWD V6',
        'BRAVADA AWD V6',
        'CONCORDE',
        'CAMRY SOLARA 4C',
        'FRONTIER PICKUP 2WD',
        'TOWN CAR',
        'MPV 2WD V6',
        'SANTA FE 2WD 4C',
        '2500 RAM PICKUP 4WD',
        'PROTEGE',
        'CARAVAN FWD V6 3.3L',
        '626 V6 2.5L V6 EFI D',
        'S SERIES 1.9L I-4 SF',
        'FOCUS 2.0L I4 SPI',
        'BONNEVILLE 3.8L V6 M',
        'RENO 2.0L I4 DI / EF',
        'INTREPID 3.5L V6 MPI',
        'BEETLE 2.0L I4 EFI',
        'FOCUS 2.0L I-4 SFI S',
        'STRATUS V6 2.7L V6 M',
        'SABLE 3.0L V6 2V /EF',
        'ESCAPE 2WD 4C 2.0L I',
        'LANCER 2.4L I4 MPI',
        'L SERIES 2.2L I4 MPI',
        'TACOMA PICKUP 2WD 4C',
        'TAURUS 3.0L V6 EFI F',
        'ESCAPE 2WD 4C 2.3L I',
        'OUTLANDER 2WD 4C 2.4',
        'ALERO 4C 2.4L I4 SFI',
        'TRIBUTE 4WD V6 3.0L',
        'PARK AVENUE 3.8L V6',
        'GRAND PRIX 3.1L V6 S',
        'MATRIX AWD',
        'L SERIES 2.0L I-4 MP',
        'ENDEAVOR FWD 3.8L V6',
        'FOCUS 2.3L I-4 DOHC',
        'MAZDA3 2.0L I-4 MPI',
        'ECHO 1.5L I4 EFI',
        'PROTEGE 5 2.0L I-4 M',
        'RENDEZVOUS AWD 3.4L',
        'F150 PICKUP 2WD V6 4',
        'XG 350',
        'SANTA FE 4WD V6',
        'TRACKER 2WD 4C',
        'SONOMA PICKUP 2WD V6',
        'HIGHLANDER 2WD 4C',
        'RAINIER RWD V6',
        'SORENTO 2WD',
        'MAGNUM V8',
        '300 3.5L V6 MPI / SM',
        'BEETLE 2.0L I4 MFI /',
        'DURANGO 2WD V6 3.7L',
        'HHR 2.2L I4 MPI / SF',
        'LACROSSE 3.6L V6 SFI',
        'XB 1.5L I-4 EFI DOHC',
        '300 3.5L / 6.0L V12',
        'PACIFICA AWD 4.0L V6',
        'MAZDA6 2.3L I4 MPI',
        'NITRO 4WD V6 3.7L V6',
        'PACIFICA FWD 4.0L V6',
        'MUSTANG V6 Unspecifi',
        'MONTANA FWD',
        '1500 SIERRA PICKUP 4',
        'PATRIOT FWD 4C',
        'AVENGER',
        'COMMANDER 2WD V8',
        'MALIBU V6 3.5L V6 MF',
        'FORENZA 2.0L I4 DI /',
        'TERRAZA FWD V6 3.5L',
        'MAZDA6 3.0L V6 MFI /',
        'ENVOY XL 2WD V8',
        'SEDONA',
        'ARMADA 4WD V8',
        'ENVOY 4WD 6C 4.2L I6',
        'SEBRING V6 3.0L V6 M',
        'RIO MFI I-4 1.6L DOH',
        'HHR 2.2L I-4 MPI DOH',
        'GRAND PRIX 3.8L V6 M',
        'AMANTI 3.5L V6 MPI',
        'ALTIMA 2.4L I4 EFI',
        'REGAL 3.8L V6 MFI SC',
        'TAHOE 2WD 5.3L V8 SF',
        'YUKON XL 1500 2WD 5.',
        'LE SABRE Unspecified',
        'LANCER 2.4L I4 EFI',
        'MONTANA 3.4L V6 SFI',
        'TAHOE 4WD 5.3L V8 SF',
        'MONTERO SPORT 2WD V6',
        'MONTANA 3.4L V6 EFI',
        'CAMRY V6 3.0L V6 SFI',
        'S SERIES 1.9L I4 SFI',
        'VIBE 1.8L I4 MFI / M',
        'COMMANDER 2WD V6 3.7',
        '4 RUNNER 2WD V8 4.7L',
        'SUBURBAN 1500 4WD',
        'COMMANDER 2WD V6',
        'MONTEGO 3.0L V6 EFI',
        'G5 4C 2.2L I4 MPI',
        'GALANT 4C 2.4L I4 EF',
        'ENVOY XL 4WD V8',
        'MOUNTAINEER AWD V8',
        'MOUNTAINEER AWD V6',
        'ASCENDER 2WD 6C',
        'COMMANDER 4WD V8',
        'ELEMENT 4WD',
        'CTS',
        'MONTEREY',
        'QUEST 3.5L V6 EFI /',
        'MARINER 4WD V6 3.0L',
        'G6 4C 2.4L I4 MFI /',
        'XL-7 4WD 2.7L V6 MPI',
        'COMMANDER 4WD V8 4.7',
        'ALERO 4C 2.2L I4 MPI',
        'DURANGO 2WD V8 5.7L',
        'COMMANDER 4WD V6',
        'HIGHLANDER 2WD V6 3.',
        'TAURUS X FWD V6',
        '2500HD SILVERADO PIC',
        'S40',
        '2500 RAM PICKUP 2WD',
        'YUKON XL 1500 2WD',
        'MPV 2WD V6 3.0L V6 M',
        'VIBE 1.8L I-4 MPI',
        'SUNFIRE 2.2L I4 MPI',
        'MOUNTAINEER 2WD V8',
        'AVALON',
        'COMPASS 4WD 4C',
        'DAKOTA PICKUP 4WD V6',
        'ASPEN 2WD V8',
        'MURANO 2WD V6',
        'QUEST',
        'QX4 4WD V6',
        'MIATA MX-5',
        'JETTA 4C',
        'RIO 5',
        'ION 2.2L I4 MPI / SF',
        'EXPLORER 4WD V8',
        'CONTINENTAL',
        'SRX AWD V6',
        'NITRO 4WD V6',
        'GRAND VITARA 2WD',
        'XA',
        'TAURUS 3.0L V6 SFI',
        'ENVOY XL 2WD 6C 4.2L',
        'FREESTAR FWD V6 4.2L',
        'NEON 2.0L I4 SFI / S',
        'OPTIMA V6 MFI V6 2.7',
        'ACCENT MFI I-4 1.6L',
        'G6 4C 2.4L I-4 MPI',
        'EXPEDITION 2WD V8 4.',
        'FOCUS 2.0L I-4 SFI D',
        'SEBRING 4C 2.4L I-4',
        'ALTIMA 2.5L I4 EFI',
        'EXPEDITION 4WD V8 4.',
        'RELAY 2WD V6 3.5L V6',
        'SUBURBAN 1500 2WD 5.',
        'VITARA 2WD 4C MFI V6',
        'CANYON PICKUP 2WD I5',
        'ENVOY XL 2WD V8 5.3L',
        'DURANGO 4WD V8 SEFI',
        'SENTRA 1.8L I4 EFI /',
        'VERONA 2.5L I6 MPI',
        'ALTIMA MFI I-4 2.5L',
        'AXIOM 2WD V6 3.5L V6',
        'MARINER 4WD 4C',
        'SEBRING V6 MFI V6 2.',
        'COBALT 2.2L I-4 MPI',
        'S10 PICKUP 2WD 4C 2.',
        'YUKON 4WD V8 4.8L V8',
        'S10 PICKUP 4WD V6 4.',
        'SPECTRA 5 2.0L I4 EF',
        'SANTA FE 2WD 4C 2.4L',
        'COLORADO PICKUP 4WD',
        'FOCUS 2.0L I4 EFI',
        'AVEO 1.6L I-4 MPI DO',
        'SUBURBAN 1500 4WD 5.',
        'ECLIPSE 3.8L V6 MPI',
        'CAMRY 4C 2.4L I-4 SF',
        'SABLE 3.0L V6 4V /EF',
        'MILAN 4C 2.3L I4 EFI',
        'SPORTAGE 2WD 4C 2.7L',
        'I-280 PICKUP 2WD 4C',
        'RONDO 4C',
        'MONTE CARLO 3.9L V6',
        'CAMRY 4C 2.4L I4 SFI',
        'TRIBUTE 2WD 4C 2.3L',
        'IMPALA 3.5L V6 SFI F',
        'MONTERO SPORT 4WD V6',
        'YUKON 2WD V8 4.8L V8',
        'MAGNUM V8 5.7L V8 SF',
        'AZERA 3.8L V6 MPI',
        'CANYON PICKUP 4WD I5',
        'PT CRUISER 2.4L I4 D',
        'UPLANDER AWD V6',
        'XL-7 2WD',
        'GS450H',
        'MONTE CARLO 3.8L V6',
        'ELEMENT 4WD 2.4L I4',
        'G6 V6 3.5L V6 MFI /',
        'TORRENT FWD V6 3.4L',
        'L SERIES 2.2L I4 SFI',
        'RENDEZVOUS FWD 3.5L',
        'ALERO 4C 2.2L I-4 MP',
        'GALANT 4C Multiple E',
        'COMPASS 2WD 4C 2.4L',
        'VIBE AWD MFI I-4 1.8',
        'G35',
        'RAINIER AWD V6',
        'GS300',
        'BONNEVILLE',
        'ODYSSEY',
        'OUTLANDER AWD 4C',
        'NAVIGATOR 4WD V8',
        'TORRENT AWD V6',
        'S10 PICKUP 2WD V6',
        'OPTIMA',
        'YUKON 2WD V8',
        'SABLE 3.0L V6 EFI SO',
        'MONTEREY 4.2L V6 SPI',
        'AVEO 1.6L I4 DOHC',
        'GALANT V6 3.0L V6 EF',
        'SENTRA 1.8L I-4 EFI',
        'NAVIGATOR 2WD V8 5.4',
        'MARINER 2WD 4C 2.3L',
        '300M 3.5L V6 MPI',
        'PROTEGE 2.0L I4 EFI',
        'VOYAGER FWD 4C 2.4L',
        'XTERRA 4WD V6 3.3L V',
        'CAVALIER 4C 2.2L I-4',
        'G6 V6 3.9L V6 SFI',
        'OPTIMA V6 2.7L V6 MP',
        'GALANT V6 3.8L V6 MP',
        'FOCUS 2.0L I4 MFI /',
        'RAINIER RWD V6 4.2L',
        'MAZDA3 2.0L I4 MFI /',
        'SPORTAGE 2WD V6 2.7L',
        'PILOT 3.5L V6 MPI',
        'SEDONA 3.8L V6 MPI',
        'CAVALIER 4C 2.4L I-4',
        'RAINIER AWD V6 4.2L',
        'NITRO 2WD V6 3.7L V6',
        'OUTLANDER 2WD 4C',
        'CAMARO V6',
        'VOYAGER FWD V6 3.3L',
        'XB 1.5L I4 EFI',
        'EXPLORER 2WD V8 4.6L',
        'LE SABRE 3.8L V6 MPI',
        'TRIBUTE 2WD V6 3.0L',
        'VERONA 2.5L I6 DI /',
        'ECLIPSE 2.4L I4 EFI',
        'B3000 PICKUP 2WD V6',
        'GALANT 4C 2.4L I-4 E',
        'REGAL 3.8L V6 MFI',
        'MAZDA3 2.3L I4 MFI /',
        'IMPALA 3.8L V6 MFI',
        'SPECTRA 2.0L I-4 EFI',
        'STRATUS V6 3.0L V6 E',
        'XTERRA 4WD V6',
        'CARAVAN GRAND AWD V6',
        'SX4',
        'YUKON AWD V8',
        'PATHFINDER 4WD V6',
        'CR-V 4WD',
        'TUCSON 2WD V6',
        'COMPASS FWD 4C',
        'PATHFINDER 2WD V6',
        'TUCSON 4WD 4C',
        'ASCENDER 4WD 6C',
        'SPECTRA 5',
        'TUCSON 4WD V6',
        '350Z MFI V6 3.5L DOH',
        'GRAND VITARA 4WD 2.7',
        'CAMRY 4C 2.4L I-4 EF',
        'XL-7 4WD 2.7L V6 MFI',
        'TAURUS 3.0L V6 EFI D',
        'L SERIES 3.0L V6 EFI',
        'AERIO 2.0L I4 EFI',
        'SEQUOIA 2WD 4.7L V8',
        'MAZDA3 2.0L I4 MPI',
        'ALTIMA MFI V6 3.5L D',
        'TUCSON 2WD 4C 2.0L I',
        'SPORTAGE 4WD 2.0L I4',
        'UPLANDER AWD V6 3.5L',
        'MAZDA6 3.0L V6 MPI',
        'COMMANDER 4WD V6 3.7',
        'ES300 3.0L V6 EFI',
        'ENVOY 4WD V8 5.3L V8',
        'COUPE 1.9L I-4 SFI D',
        'PATHFINDER 4WD V6 3.',
        'XTERRA 2WD 4C 2.4L I',
        'L SERIES 2.0L I4 MPI',
        'SONOMA PICKUP 2WD 4C',
        'RENO 2.0L I-4 EFI DO',
        'TUNDRA PICKUP 4WD V8',
        'CONTINENTAL 4.6L V8',
        'AURA 3.5L V6 SFI',
        'MPV 2WD V6 MFI V6 3.',
        'MONTANA AWD 3.5L V6',
        'MURANO AWD V6 3.5L V',
        'SABLE 3.0L V6 EFI 4B',
        'CR-V 4WD 2.0L I-4 MP',
        'PATHFINDER 4WD V6 MF',
        'ECHO Multiple Engine',
        '300C',
        'SRX AWD V8 4.6L V8 S',
        'ION 2.2L I-4 MPI DOH',
        'max_valueIMA 3.5L V6 MPI /',
        'SANTA FE 2WD V6 3.5L',
        'IMPALA 3.8L V6 MFI S',
        'YUKON 4WD V8 5.3L V8',
        'VUE 2WD 4C 2.2L I-4',
        'FOCUS 2.3L I4 DOHC',
        'TRACKER 4WD 4C',
        'SOLSTICE',
        'ZEPHYR',
        'TL',
        'YUKON 4WD V8',
        'TRIBUTE 4WD 4C',
        'ESCORT 2.0L I-4 EFI',
        'CHEROKEE 2WD 6C 4.0L',
        'COMPASS 4WD 4C 2.4L',
        'FOCUS 2.0L I4 SFI /',
        'MAZDA3 2.3L I4 MPI',
        'ESCORT 2.0L I4 EFI',
        'S10 PICKUP 2WD V6 MF',
        'DURANGO 4WD V8 5.9L',
        'SIERRA 1500',
        'HHR 2.4L I4 MPI',
        'CAMRY 4C 2.4L I4 EFI',
        'TRACKER 4WD V6',
        'PILOT',
        'ES330',
        'SPORTAGE 4WD V6',
        'F150 PICKUP 4WD V6',
        'RAIDER 2WD V6',
        'VIBE AWD',
        'AZERA',
        'COUPE',
        'AVIATOR 2WD V8',
        '626 V6',
        'GRAND MARQUIS 4.6L V',
        'XB 1.5L I-4 MPI',
        'MUSTANG V8',
        'TC 2.4L I-4 EFI DOHC',
        'SCION XB',
        'CANYON PICKUP 2WD 4C',
        'SEQUOIA 2WD',
        'TC',
        'YUKON 2WD V8 5.3L V8',
        'ESCAPE 4WD 4C 2.3L I',
        'TIBURON MFI I-4 2.0L',
        'PROTEGE MFI I-4 1.6L',
        'SPORTAGE 2WD V6',
        'RANGER PICKUP 4WD V6',
        'ESCAPE 4WD 4C',
        'TRAILBLAZER 2WD V8',
        'AERIO',
        'ION 2.0L I-4 MPI DOH',
        'ENVOY 4WD 6C 4.2L I-',
        'GRAND PRIX 5.3L V8 S',
        'HHR 2.4L I4 MPI / SF',
        'ALERO 4C 2.4L I-4 SF',
        'ASCENDER 4WD 6C 4.2L',
        'OUTLANDER AWD 4C 2.4',
        'GS300 3.0L I6 EFI',
        'ION 2.2L I-4 EFI DOH',
        'ENVOY XL 4WD V8 5.3L',
        'MARINER 4WD 4C 2.3L',
        'MONTANA AWD',
        'TSX',
        'ES300',
        'LEGACY',
        'LUCERNE V6',
        'CAMARO V6 3.8L V6 MF',
        'COROLLA 1.8L I4 EFI',
        'QUEST 3.5L V6 MPI',
        'IMPALA V6 3.9L V6 SF',
        'ECLIPSE EI V6 3.0L S',
        'TAURUS X FWD V6 3.5L',
        'FUSION V6 3.0L V6 EF',
        'max_valueIMA 3.0L V6 EFI D',
        'CTS 3.2L V6 SFI',
        'MONTERO 4WD V6 3.5L',
        'I35 3.5L V6 MPI DOHC',
        'STRATUS 4C 2.4L I-4',
        'G20 2.0L I4 EFI',
        'XG 350 3.5L V6 EFI D',
        'MOUNTAINEER AWD V8 4',
        'VUE AWD 4C',
        '300C 5.7L V8 SFI / S',
        'XL-7 2WD 2.7L V6 MFI',
        'GRAND VITARA 2WD 2.7',
        'SUBURBAN 2500 4WD 6.',
        'INTREPID',
        'BEETLE 2.0L I4 MPI',
        'EXPLORER AWD V6 4.0L',
        'MUSTANG V8 4.6L V8 E',
        'RX400H AWD',
        'SUBURBAN 2500 4WD',
        'F150 PICKUP 4WD V8 5',
        'VUE 2WD V6 3.5L V6 M',
        'GRAND AM 4C 2.4L I-4',
        'PATHFINDER 2WD V6 MF',
        'MATRIX 2WD 1.8L I-4',
        'XTERRA 2WD V6 4.0L V',
        'MURANO 2WD V6 3.5L V',
        'PATHFINDER 2WD V6 4.',
        'IMPALA 5.3L V8 SFI',
        'CTS 3.6L V6 SFI',
        '626 4C 2.0L I-4 EFI',
        'STRATUS V6 2.4L I-4',
        'L SERIES 2.2L I-4 EF',
        'LANCER 2.0L I-4 MPI',
        'COROLLA 1.8L I-4 EFI',
        'MATRIX 2WD Multiple',
        'PROTEGE 2.0L I-4 EFI',
        'SEBRING 4C 2.4L I4 M',
        'SPORTAGE 2WD 4C MFI',
        'VIBE AWD 1.8L I4 MPI',
        'MDX 4WD 3.5L V6 SOHC',
        'TUNDRA PICKUP 2WD V6',
        'VUE 2WD V6 3.0L V6 S',
        '4 RUNNER 2WD V6 3.4L',
        'MOUNTAINEER 2WD V6 4',
        'ES300 3.0L V6 EFI DO',
        'GRAND AM V6 3.4L V 6',
        'ACCENT 1.6L I-4 MPI',
        'COUPE 1.9L I-4 SFI S',
        'AURA V6 3.5L V6 SFI',
        'ACCORD 4C 2.3L I-4 E',
        'COOPER S',
        '3.2 TL',
        'MONTERO 4WD V6',
        '1500HD SILVERADO PIC',
        'MARINER 2WD 4C',
        'MAZDA6 3.0L V6 MPI D',
        'COROLLA Multiple Eng',
        'TUCSON 2WD V6 2.7L V',
        'XA 1.5L I4 EFI',
        'TACOMA PICKUP 2WD V6',
        'CELICA',
        'MDX 4WD',
        '4 RUNNER 2WD V6',
        '350Z',
        'ECHO',
        'S60',
        'CARAVAN',
        'SILHOUETTE 3.4L V6 S',
        'ENDEAVOR AWD 3.8L V6',
        'ENVOY XL 4WD 6C 4.2L',
        'INTREPID 2.7L V6 SFI',
        'CAMRY V6 3.0L V6 EFI',
        'CIVIC MFI I-4 1.7L S',
        'RAV-4 2WD Multiple E',
        'S10 PICKUP 4WD V6 MF',
        'MALIBU 4C 2.4L I4 MP',
        'GRAND AM 4C 2.2L I-4',
        'FX35 AWD',
        'FOCUS Multiple Engin',
        'CAMRY V6 3.5L V6 SFI',
        'TUCSON 4WD V6 2.7L V',
        'H3 3.5L I5 MPI / SFI',
        'VENTURE FWD V6 3.5L',
        'VENTURE AWD V6 3.4L',
        'SORENTO 2WD 3.8L V6',
        'VUE AWD 4C 2.2L I-4',
        'DURANGO 2WD V8 5.9L',
        'IMPREZA',
        'DAKOTA PICKUP 2WD 4C',
        'MOUNTAINEER 2WD V8 4',
        'TUCSON 2WD V6 MFI V6',
        'SILHOUETTE 3.4L V 6',
        'INTREPID 3.5L V6 EFI',
        'COMMANDER 2WD V8 4.7',
        'ACCORD 4C MFI I-4 2.',
        'MAZDA5 2.3L I4 MFI /',
        'EXPLORER 4WD V8 4.6L',
        'SABLE 3.0L V6 EFI 2B',
        'YUKON XL 1500 4WD 5.',
        'B2300 PICKUP 2WD 4C',
        'RAV-4 2WD',
        'NAVIGATOR 2WD V8',
        '1500HD SIERRA PICKUP',
        '626 4C',
        'SEQUOIA 4WD 4.7L V8',
        '3.2 CL 3.2L V 6 NA S',
        'QX4 2WD V6 3.5L V6 M',
        'TIBURON 2.7L V6 MPI',
        'ESCORT 4-FI-2.0L',
        'CAMRY SOLARA 4C 2.4L',
        'HIGHLANDER 4WD V6',
        'CAMRY 4C Multiple En',
        'TRACKER 2WD V6 2.5L',
        '2500 SILVERADO PICKU',
        'FIT',
        'LS V6',
        'CIVIC 1.7L I-4 MPI S',
        'MURANO AWD V6',
        'FJ CRUISER 4WD V6',
        'XG 300',
        'F150 PICKUP 4WD V8 4',
        'ECLIPSE 3.0L V6 EFI',
        'XL-7 2WD 2.7L V6 DI',
        'MONTERO 4WD V6 3.8L',
        'TRACKER 4WD 4C 2.0L',
        'TIBURON MFI V6 2.7L',
        'AERIO 2.3L I-4 SFI D',
        'ACCENT 1.5L I-4 EFI',
        '2500HD SIERRA PICKUP',
        'SIENNA 3.0L V6 MPI',
        'WRANGLER 6C',
        'RSX',
        'RAV-4 4WD',
        'PROTEGE 5',
        'CARAVAN SE',
        'CHEROKEE 2WD 6C',
        'CHEROKEE 4WD 6C',
        'B3000 PICKUP 4WD V6',
        'PRIZM',
        '300C 5.7L V8 SFI',
        'SRX AWD V6 3.6L V6 S',
        'MPV 2WD V6 MFI V6 2.',
        'RODEO 2WD 4C MFI I-4',
        'AVALANCHE 2500 2WD V',
        'ECLIPSE 2.4L I-4 EFI',
        'PATHFINDER 2WD V6 3.',
        'AVENGER V6 Unspecifi',
        'CAMRY SOLARA 4C Mult',
        'CROWN VICTORIA 4.6L',
        'AVIATOR 2WD V8 4.6L',
        'AVALON 3.0L V6 EFI D',
        'GRAND AM V6 Unspecif',
        'MATRIX 2WD Unspecifi',
        'CR-V 4WD 2.4L I4 MPI',
        'ECHO 1.5L I-4 EFI DO',
        'MONTANA 3.4L V 6 NA',
        'CIVIC 1.7L I4 MFI /',
        'TAURUS 3.5L V6 24V /',
        'LS V8',
        'SONATA 4C 2.4L I-4 M',
        'OUTBACK',
        'LS V6 3.0L V6 EFI',
        '3.2 TL 3.2L V6 EFI',
        'ESCAPE',
        'BEETLE 2.0L I4 EFI /',
        'PRIZM 1.8L I-4 SFI D',
        'CAMRY V6 3.0L / 3.3L',
        'DAKOTA PICKUP 4WD V8',
        'PATRIOT 2WD 4C 2.4L',
        'MAGENTIS 4C',
        'I30',
        'FIREBIRD V6',
        'LHS',
        'ENTOURAGE',
        'RONDO V6 2.7L V6 MPI',
        'VERONA',
        'AXIOM 4WD V6 3.5L V6',
        'FOCUS 2.0L I-4 SPI',
        'VERONA 2.5L I-6 MPI',
        'WRANGLER 6C 4.0L I-6',
        '3.2 TL 3.2L V6 FI DO',
        'F250 PICKUP 4WD V8',
        'RIO 5 1.6L I4 MPI',
        'VUE AWD V6 3.5L V6 M',
        'REGAL 3.8L V6 SFI',
        'YUKON XL 1500 AWD 6.',
        'PATHFINDER 4WD V6 4.',
        'MAZDA6 2.3L I-4 MPI',
        'CR-V 2WD',
        'GALANT 4C 2.4L I4 MP',
        'CIVIC 1.7L I4 MPI',
        'ZEPHYR 3.0L V6 SFI',
        'CAVALIER 4C 2.2L I 4',
        'ASCENDER 2WD V8 5.3L',
        'RAINIER RWD V8',
        'FRONTIER PICKUP 4WD',
        'RELAY AWD V6',
        'ECLIPSE V6',
        'G35 3.5L V6 MPI',
        'CAMRY 4C EI I-4 2.2L',
        'G8 V8',
        'TOWN & COUNTRY AWD V',
        'CONCORDE 2.7L V6 SFI',
        'LIBERTY 2WD 4C 2.4L',
        'AERIO 2.3L I4 SFI',
        'COMMANDER',
        'CALIBER 1.8L I4 SFI',
        'F250 PICKUP 2WD V8',
        'EDGE FWD V6',
        'TITAN PICKUP 4WD V8',
        'M35',
        'STS V6',
        'CROSSFIRE 3.2L V6 MP',
        'RAINIER AWD V8',
        'ENVOY 2WD V8',
        'TOUAREG V8',
        'MAZDA3 2.3L I-4 MPI',
        'ALTIMA Multiple Engi',
        'FOCUS 2.3L I4 SFI',
        'RELAY 2WD V6 3.9L V6',
        'TC 2.4L I4 16V / EFI',
        'G35 3.5L V6 DOHC',
        'COOPER S 1.6L I4 EFI',
        'FOCUS 2.3L I4 MFI',
        'COMPASS 2WD 4C',
        'RABBIT',
        'BRAVADA 2WD V6 4.2L',
        'SONATA V6 MFI V6 2.7',
        'GRAND VITARA 4WD',
        'SUNFIRE 2.2L I 4 NA',
        'LS V6 3.0L V6 EFI DO',
        'RENDEZVOUS AWD 3.5L',
        'SEQUOIA 4WD',
        'SUNFIRE 2.2L I-4 MPI',
        'AERIO 2.3L I4 DI / S',
        'S10 PICKUP 2WD V6 4.',
        'AERIO AWD',
        'LIBERTY 4WD 4C',
        'RONDO 4C 2.4L I4 DI',
        'EDGE AWD V6',
        'GRAND VITARA 4WD MFI',
        'HIGHLANDER 2WD 4C 2.',
        'ESCORT',
        'I-370 PICKUP 2WD 5C',
        'ELEMENT 2WD 2.4L I-4',
        'XG 300 Unspecified',
        'ESCORT 2.0L I-4 SPI',
        'MAGNUM V6 MFI V6 3.5',
        '300M 3.5L V6 MPI HO',
        'JOURNEY FWD V6',
        'ACCORD 4C 2.3L I-4 S',
        'SEBRING V6 2.4L I4 S',
        'XD',
        'NAVIGATOR 4WD V8 5.4',
        'Pacifica',
        'TRAILBLAZER 4WD V8',
        'HIGHLANDER 4WD 4C',
        'AVENGER V6 2.7L V6 M',
        'LUCERNE V6 3.8L V6 S',
        'SABLE 3.5L V6 24V /',
        'CONCORDE 3.2L V6 EFI',
        'RX300 2WD 3.0L V6 EF',
        'ACCORD 4C 2.3L I4 EF',
        'RAINIER RWD V8 5.3L',
        'CR-V 2WD 2.0L I 4 NA',
        'ESCALADE 2WD',
        'F250 PICKUP 2WD V8 5',
        'RX300 2WD',
        'STRATUS V6 2.7L V6 S',
        'OUTLANDER 2WD V6'])
            nationality=  st.selectbox('The Manufacturer\'s country',['OTHER ASIAN', 'AMERICAN', 'TOP LINE ASIAN', 'OTHER'])
            primeunit=  st.selectbox('Identifies if the vehicle would have a higher demand than a standard purchase',['YES','NO'])
            purchdate=  st.date_input('The Date the vehicle was Purchased at Auction')
            refid=  st.number_input('Unique (sequential) number assigned to vehicles',min_value=1,max_value=80000)
            size=  st.selectbox('The size category of the vehicle (Compact, SUV, etc.)',['MEDIUM',
        'LARGE TRUCK',
        'COMPACT',
        'LARGE',
        'VAN',
        'MEDIUM SUV',
        'LARGE SUV',
        'SPECIALTY',
        'SPORTS',
        'CROSSOVER',
        'SMALL SUV',
        'SMALL TRUCK',])
            submodel=  st.selectbox('Vehicle Submodel',['4D SEDAN I',
        'QUAD CAB 4.7L SLT',
        '4D SEDAN SXT FFV',
        '4D SEDAN',
        '2D COUPE ZX3',
        '4D SEDAN ES',
        '4D SEDAN EX',
        '4D SEDAN SE',
        '4D SEDAN SEL',
        'REG CAB 4.3L',
        'REG CAB 4.2L XL',
        'min_valueIVAN 3.3L',
        'min_valueIVAN 3.8L',
        '2D COUPE',
        '4D SUV 4.2L',
        '4D CUV 2.2L',
        '4D UTILITY 4.2L SLE',
        '2D COUPE SS',
        'PASSENGER 3.4L',
        '4D SUV 2.2L LS',
        '4D SEDAN LS PREMIUM',
        '4D SUV 5.7L SLT',
        'min_valueIVAN 3.8L SXT',
        '4D UTILITY 5.3L FFV LS',
        '2D SUV 4.0L SPORT',
        '4D SUV-PICKUP 5.3L',
        'PASSENGER 3.8L LX',
        'PASSENGER 3.9L LX',
        '4D WAGON SXT',
        '4D SEDAN 1.8',
        '4D SPORT TOURER',
        '4D SEDAN LS 3.5L FFV',
        'QUAD CAB 5.7L',
        '4D SPORT UTILITY',
        '4D SEDAN CE',
        '4D SEDAN GT',
        'QUAD CAB 4.7L',
        '4D SEDAN LEVEL 2',
        '4D SUV 4.7L',
        '4D SUV 4.7L ADVENTURER',
        '4D SEDAN GLS',
        '4D SPORT UTILITY SPORT EDITION',
        '4D SEDAN GXP',
        '4D WAGON SPORT',
        '4D SUV',
        'QUAD CAB 3.7L ST',
        '4D SUV 5.3L',
        '4D SEDAN LS',
        '4D SUV 4.6L XLT',
        '4D SUV 4.7L ST',
        '4D SPORT UTILITY EX',
        '4D SUV 2.2L LT',
        '4D SEDAN SES',
        '4D CUV 3.0L SEL',
        'CREW CAB 5.4L KING RANCH',
        '4D SUV 4.2L LS',
        '4D SUV HARDTOP 2.5L LT',
        'QUAD CAB 5.7L SLT',
        '4D SUV 3.7L',
        '4D SUV 4.6L XLS',
        'QUAD CAB 4.7L FFV BIG HORN',
        '4D SEDAN GL1',
        'min_valueIVAN 3.3L LX',
        '4D SEDAN LE',
        'WAGON 2.7L',
        '4D SUV LS',
        '4D SUV SPORT',
        '4D SEDAN LEVEL 1',
        '4D CUV 3.0L SE',
        '4D SEDAN L200',
        '4D SUV LIMITED',
        '4D WAGON',
        '5D SEDAN GS',
        '4D SUV 4.6L EDDIE BAUER',
        '4D SUV 5.4L EDDIE BAUER',
        'REG CAB 3.7L',
        '4D min_valueIVAN EXT 3.4L GLS',
        '4D CUV 3.0L XLT',
        '4D SEDAN LEVEL 3',
        '2D EXT CAB 3.0L EDGE',
        '4D WAGON ZTW',
        '2D COUPE LS',
        '4D SUV 4.7L SLT',
        'PASSENGER EXT 3.5L',
        'EXT CAB 4.8L',
        '4D SUV 4.0L FFV XLT',
        '4D SPORT UTILITY LS',
        '4D SEDAN SEL FFV',
        '4D SEDAN SE FFV',
        'WAGON 3.5L',
        '4D SPORT TOURING',
        '4D SEDAN ZX4 SE',
        '4D SEDAN GL',
        '4D SEDAN LT 3.5L',
        '4D CUV',
        '4D SEDAN S',
        'EXT CAB 3.7L',
        'PASSENGER EXT 3.5L LS',
        'REG CAB 3.0L EDGE',
        'min_valueIVAN 3.3L FFV SPORT',
        '4D SPORT UTILITY I',
        '4D SUV CX',
        '4D SEDAN LT 3.5L FFV',
        'REG CAB 4.2L STX',
        '4D SEDAN SE1',
        '4D WAGON SE',
        '4D SEDAN LX AUTO',
        '4D CUV 2.3L XLS',
        '2D COUPE SE',
        '4D SEDAN ZX4',
        'REG CAB 2.8L',
        '4D CUV 2.7L',
        '4D WAGON LAREDO',
        '4D SEDAN SE COMFORT',
        '4D SEDAN LX',
        'min_valueIVAN 3.3L SPORT',
        '4D SEDAN 2.7L SE',
        '4D SPORT',
        '4D SEDAN SXT',
        '4D SEDAN GS',
        '4D SUV HARDTOP 2.5L',
        '4D SEDAN LT',
        '4D SPORT UTILITY SE',
        '4D SEDAN XE',
        'REG CAB 4.6L STX',
        '4D SPORT UTILITY S',
        'EXT CAB 4.6L STX',
        '4D WAGON CX',
        '4D SUV RENEGADE',
        'min_valueIVAN 3.3L SE',
        '4D SEDAN TOURING TURBO',
        '2D CONVERTIBLE LX',
        '4D SEDAN LTZ',
        'PASSENGER 3.5L LS',
        '4D CUV 2.7L GLS',
        '4D SEDAN ZTS',
        '4D HATCHBACK S',
        '4D SUV 4.0L FFV XLS',
        'min_valueIVAN 3.8L SPORT',
        '4D SUV 3.7L SLT',
        'EXT CAB 4.6L FX2 SPORT',
        '4D SEDAN PKG1',
        '2D CONVERTIBLE GTC',
        '4D SEDAN LT 3.9L',
        'MAZDA3 4D I SPORT',
        '4D PASSENGER 3.8L SE',
        '4D SEDAN GTP',
        '4D SEDAN LS SPORT',
        'PASSENGER EXT 3.4L LS',
        '4D SUV 5.4L XLT',
        '4D SEDAN 2.7L',
        '4D SEDAN CLASSIC',
        '4D SUV 3.0L',
        '2D CONVERTIBLE TOURING',
        '4D SEDAN TOURING',
        'SPORT UTILITY',
        '2D SPYDER GT',
        '4D SUV LT',
        '4D SEDAN LXI',
        'PASSENGER EXT 3.4L',
        '4D SEDAN SE-R',
        'min_valueIVAN 3.8L LXI',
        'EXT CAB 5.3L LS',
        '4D SUV 4.8L LS',
        '4D SEDAN GT2',
        '4D SPORT UTILITY LX',
        '2D COUPE LT',
        '4D SUV 4.0L XLT',
        '2D COUPE EX AUTO',
        '4D CUV 3.0L XLS',
        '2D COUPE GS',
        '4D SEDAN EXECUTIVE',
        '4D SEDAN PREMIER',
        '4D SEDAN EX AUTO',
        '4D SUV 5.7L LIMITED',
        'min_valueIVAN 2.4L',
        '4D SEDAN LIMITED',
        'CREW CAB 5.3L',
        '4D SEDAN SL2',
        '4D PASSENGER 3.8L SEL',
        '4D SEDAN GXE',
        '4D SEDAN SE AUTO',
        '4D SEDAN ES HIGHLINE',
        '4D SUV 5.9L SLT',
        'EXT CAB 5.3L',
        'PASSENGER 3.9L',
        '4D SEDAN SL1',
        '4D SEDAN CUSTOM',
        'QUAD CAB 3.7L',
        '4D SPORT UTILITY ES',
        '4D SEDAN LUXURY',
        'REG CAB 2.2L FFV',
        '4D SEDAN SES DURATEC',
        'CREW CAB 4.6L XLT',
        '4D SEDAN DE',
        '4D SEDAN GL2',
        '4D SUV 5.3L FFV LS',
        '4D SEDAN 1.8S',
        '2D COUPE SE AUTO',
        '4D SEDAN 3.5L',
        '2D HATCKBACK SI 5SP',
        'WAGON 3.5L SXT',
        '4D SEDAN CX',
        '2D QUAD COUPE LEVEL 3',
        '4D SEDAN GLE',
        '2D CONVERTIBLE',
        '4D SEDAN 3.5L SE',
        'min_valueIVAN 3.3L SXT',
        '4D SPORT UTILITY 2.5X',
        '4D SPORT UTILITY XE',
        'EXT CAB 4.7L SLT',
        '2D COUPE GT1',
        '2D CONVERTIBLE SE',
        '4D min_valueIVAN EXT 3.4L',
        '4D HATCHBACK GS',
        '4D SUV 5.3L LS',
        'EXT CAB 4.3L',
        '4D UTILITY 4.2L',
        'min_valueIVAN 3.8L EX',
        '4D SEDAN XR',
        'REG CAB 2.3L EDGE',
        '4D SEDAN LT 3.8L FFV',
        '2D COUPE GT',
        '2D CONVERTIBLE DREAM CRUISER',
        '4D PASSENGER 3.9L SES',
        '2D COUPE SVT',
        'min_valueIVAN 3.3L FFV SE',
        '4D CUV 3.0L LIMITED',
        '4D SUV 4.0L',
        'QUAD CAB 4.7L SPORT',
        '2D COUPE GLS',
        '4D WAGON LW300',
        'REG CAB 3.9L',
        '4D SEDAN LS CLASSIC',
        'EXT min_valueIVAN 3.3L LX',
        'EXT CAB 5.4L XL',
        '4D SUV 4.0L XLS',
        '2D QUAD COUPE LEVEL 2',
        'PASSENGER 3.9L SE',
        '2D COUPE GL2',
        '4D HARDTOP EX',
        '4D SUV 4.8L',
        'EXT CAB 5.3L SLE',
        'EXT CAB 4.8L LS',
        'EXT CAB 4.6L XLT',
        'CREW CAB 5.6L SE',
        '4D SUV 2.2L 1LT',
        '4D min_valueIVAN EXT 3.5L',
        '4D SEDAN LS 3.5L',
        '2D COUPE SXT',
        '4D SUV 4.2L LT',
        '4D WAGON LX',
        'REG CAB 4.7L SLT',
        '4D WAGON GT',
        'CARGO EXT 3.9L',
        '4D SEDAN VALUE',
        'EXT CAB 5.6L',
        '2D COUPE GTP',
        'EXT CAB 5.4L XLT',
        'REG CAB 4.7L',
        '2D COUPE GL',
        '4D CUV 3.0L',
        'UTILITY',
        '4D SEDAN LIMITED AWD',
        '4D SEDAN GT1',
        '4D CUV GLS',
        '4D SUV HARDTOP 2.0L',
        'min_valueIVAN 2.4L SE',
        'QUAD CAB 3.9L SLT',
        'EXT CAB 3.9L',
        'EXT CAB 5.4L LARIAT',
        '4D WAGON LS PREMIUM',
        '4D SEDAN CARTIER',
        'EXT CAB 4.7L LIMITED',
        'min_valueIVAN 3.8L EL',
        '4D WAGON SEL DURATEC',
        '4D SPORT UTILITY 5 PASS',
        'EXT CAB 2.4L XE',
        'EXT CAB 3.5L LS',
        'WAGON ES',
        'min_valueIVAN 3.3L LX POPULAR',
        '4D WAGON LIMITED',
        '4D CUV DLX',
        'REG CAB 5.7L ST',
        '4D SEDAN SPECIAL',
        'REG CAB 4.6L XLT',
        '4D SEDAN CXL',
        '4D SEDAN SE SVG',
        '4D SUV 4.0L SPORT TRAC',
        'PASSENGER 3.4L VALUE',
        'CREW CAB 5.4L HARLEY DAVIDSON',
        '4D CUV 2.0L XLS',
        '4D SPORTBACK LS',
        'min_valueIVAN 3.3L EL',
        'REG CAB 2.4L',
        '2D SUV 4.0L SPORT XLS',
        '4D WAGON LW200',
        '4D SPORT UTILITY XLS',
        '2D SEDAN',
        'PASSENGER 3.8L',
        'REG CAB 3.5L LS',
        '4D SUV 4.7L SPORT',
        '4D EXT CAB 3.0L FFV XLT',
        '4D CUV 3.5L',
        'min_valueIVAN 2.4L LX',
        'PASSENGER 3.9L SEL',
        'REG CAB 2.3L',
        '4D SEDAN L300',
        '4D min_valueIVAN 3.4L',
        '4D SUV 3.7L SXT',
        '4D SUV CXL',
        '4D SEDAN SE COMFORT DURATEC',
        'WAGON R/T',
        '4D SEDAN ZX4 SES',
        'QUAD CAB 3.7L SLT',
        '4D SEDAN 3.5L AWD',
        'REG CAB 4.8L LS',
        '4D SEDAN CXS',
        'PASSENGER EXT 3.9L LS',
        'QUAD CAB 3.7L SPORT',
        'PASSENGER EXT 3.5L LT',
        '4D SUV 4.7L SXT',
        '4D SUV 5.7L',
        'EXT CAB 4.3L LS',
        '4D SEDAN AWD SE',
        '4D SEDAN DX AUTO',
        '4D SEDAN LX 5SP',
        '4D SEDAN SE AWD',
        '4D WAGON CINCO',
        '4D SEDAN PREMIER AWD',
        'EXT CAB 5.4L FX2 SPORT',
        'QUAD CAB 5.7L BIG HORN',
        '4D SUV 4.7L FFV SXT',
        '4D UTILITY 5.3L SLE',
        '4D WAGON EX',
        'PASSENGER 4.2L SE',
        'CREW CAB 5.4L LARIAT',
        '4D SEDAN GT TURBO',
        '4D SPORT UTILITY LE',
        '2D COUPE LIMTED',
        '4D SEDAN RALLIART',
        'REG CAB 3.7L ST',
        'EXT CAB 3.0L EDGE',
        'PASSENGER EXT 3.9L LT',
        '4D SUV 5.3L FFV',
        '4D UTILITY 5.3L LS',
        'CREW CAB 5.3L SLE',
        'REG CAB 5.3L',
        '4D UTILITY XUV 4.2L SLE',
        '4D UTILITY 5.3L SLT',
        '4D SUV 4.6L',
        '2D COUPE EX 5SP',
        '5D HATCHBACK I',
        'EXT CAB 2.8L LS',
        'REG CAB 3.7L SXT',
        '5D SEDAN S',
        '2D SPYDER GTS',
        '4D PASSENGER 4.2L LIMITED',
        '4D WAGON S',
        '4D SUV 3.0L PREMIER',
        '2D COUPE GL1',
        '4D CUV DELUXE',
        '4D SUV 5.7L HEMI SLT',
        '4D SEDAN ZX4 ST',
        '4D CROSSOVER SEL',
        'REG CAB 6.0L',
        '4D SEDAN 2.4I',
        'min_valueIVAN 3.8L LIMITED',
        '4D SEDAN SEL AWD',
        '4D WAGON R/T',
        '3D EXT CAB 2.2L',
        '4D HATCHBACK ZX5 S',
        '4D SEDAN AWD SEL',
        'WAGON LX',
        '4D WAGON LS',
        '4D SEDAN XL',
        '4D SUV 4.0L EDDIE BAUER',
        'EXT CAB 4.2L XL',
        '4D SUV 2.4L',
        'EXT CAB 3.9L SLT',
        '4D SPORT UTILITY LIMITED FFV',
        'REG CAB 2.2L',
        '4D SEDAN GTS',
        '4D SEDAN 2.5 S',
        'QUAD CAB 4.7L ST',
        '2D EXT CAB 3.0L',
        '4D SUV 5.3L LT',
        'QUAD CAB 5.9L SLT',
        'EXT CAB 4.2L W/T',
        '4D SUV 3.0L LUXURY',
        'REG CAB 4.8L',
        '4D SUV 2.2L',
        '2D HATCHBACK',
        '4D SEDAN 2.5 SL',
        '4D SPORT UTILITY XSPORT',
        '4D SEDAN DX',
        '4D HATCHBACK',
        '4D SEDAN SEL DURATEC',
        'REG CAB 4.6L XL',
        'QUAD CAB 5.9L SPORT',
        'EXT CAB 6.0L',
        'EXT CAB 5.6L LE',
        '4D UTILITY 5.3L FFV',
        '4D HARDTOP LX',
        'CREW CAB 3.5L SL',
        'EXT CAB 4.8L SLE',
        '4D SUV 2.3L CONVENIENCE',
        'CREW CAB 6.0L LS',
        'REG CAB 5.7L SLT',
        '4D UTILITY 4.8L SLE',
        'REG CAB 5.4L XL',
        'EXT CAB 4.0L LE',
        'EXT CAB 8.1L LS',
        'CREW CAB 4.3L LS',
        'REG CAB 4.3L LS',
        'EXT CAB 3.5L',
        'REG CAB 4.3L SLE',
        'PASSENGER 3.9L LS',
        'CREW CAB 3.5L LS',
        'CREW CAB 4.7L SR5',
        '4D SEDAN AUTO',
        'CREW CAB 3.5L Z71',
        'CREW CAB 5.6L',
        '4D SUV 4.7L SL',
        'EXT CAB 2.8L',
        'min_valueIVAN 3.8L ES',
        '4D SUV 5.7L HEMI LIMITED',
        '2D COUPE R/T',
        'REG CAB 5.3L LS',
        '4D UTILITY 4.8L',
        'REG CAB 3.5L SL',
        '4D WAGON LAREDO FFV',
        '4D SEDAN SS',
        'CREW CAB 5.6L LE',
        'CREW CAB 4.8L',
        '2D COUPE EX 6SP',
        '4D SEDAN HYBRID',
        '4D SEDAN GX',
        '4D SUV SPORT 2.4L',
        'EXT CAB 3.7L SLT',
        'min_valueIVAN EX-L',
        'PASSENGER EXT 3.9L',
        'MAZDA5 GRAND TOURING',
        '4D WAGON ZX5',
        '2D COUPE LX AUTO',
        '2D COUPE RS',
        '4D SEDAN LIMITED TURBO',
        '4D SUV 4.7L LIMITED',
        '2D COUPE LX',
        '4D SUV 5.4L',
        '3D EXT CAB 4.3L',
        'REG CAB 4.7L FFV',
        '4D SEDAN R/T',
        '4D WAGON GS',
        '4D SPORT UTILITY 3.5L XLS',
        '4D SUV 4.0L FFV LIMITED',
        'EXT CAB 5.3L SL',
        '4D UTILITY 4.8L SLT',
        '4D SUV 2.3L',
        'ACCESS CAB 4.7L SR5',
        '4D SEDAN SLE',
        '5D HATCHBACK S',
        '4D SEDAN Z24',
        'WAGON DX',
        '4D SEDAN AWD',
        '2D HATCHBACK ZX3',
        'REG CAB 4.0L',
        '4D WAGON OVERLAND',
        '4D EXT CAB 3.0L EDGE',
        'EXT CAB 6.0L LS',
        '4D min_valueIVAN 3.4L VALUE',
        '4D SEDAN EX AUTO NAVIGATION',
        '4D WAGON CONVENIENCE',
        '4D SPORT UTILITY DX',
        '4D SUV 4.7L FFV SLT',
        '4D HATCHBACK AWD',
        '4D UTILITY 6.0L DENALI',
        'DOUBLE CAB 4.7L SR5',
        '4D SEDAN XRS',
        '3D COUPE SC2',
        '4D SEDAN FFV TOURING',
        '4D SEDAN GS 3.0L FFV',
        '4D UTILITY 5.3L',
        '4D WAGON GRAND TOURING',
        '4D CUV GL',
        '4D PASSENGER 3.8L SEL LIMITED',
        '4D PASSENGER 3.8L SE SPORT',
        'EXT CAB 4.7L SR5',
        '2D COUPE AUTO',
        '2D COUPE LX 5SP',
        '5D SEDAN ZX5',
        'CREW CAB 3.3L XE',
        '4D SPORT UTILITY XL7',
        '4D WAGON SE DURATEC',
        '4D SEDAN SIGNATURE',
        '4D SPORT UTILITY LIMITED',
        'REG CAB 2.5L EDGE',
        'QUAD CAB 4.7L FFV SLT',
        '3D COUPE SC1',
        '4D SPORT UTILITY 3.5L XS',
        'REG CAB 2.2L SL',
        'EXT CAB 2.2L LS',
        '4D SPORT UTILITY LEVEL 3',
        '2D HATCHBACK GS',
        'EXT CAB 4.6L LARIAT',
        '4D SPORT UTILITY SL',
        'CREW CAB 4.6L LARIAT',
        '4D SPORT UTILITY EX AUTO',
        '4D SEDAN HEMI',
        '4D WAGON SE COMFORT',
        'EXT CAB 3.5L Z71 LS',
        '4D HATCHBACK ZX5',
        'EXT CAB 3.7L SXT',
        '2D ROADSTER',
        '2D SPYDER GS',
        '4D SUV ULTRA',
        '4D PASSENGER 4.2L SEL',
        '2D HARTOP CONVERTIBLE GT',
        '4D SEDAN LS 3.6L',
        '4D SEDAN VALUE AUTO',
        '2D COUPE ZX2',
        '4D UTILITY 4.2L SLT',
        '4D SEDAN VP AUTO',
        '4D CUV 2.3L XLT',
        '4D SUV HARDTOP 2.5L ZR2',
        '5D SEDAN I',
        '2D COUPE GX',
        'BASE',
        'QUAD CAB 3.9L SPORT',
        'REG CAB 4.2L W/T',
        '4D SUV 4.0L FFV EDDIE BAUER',
        'DOUBLE CAB DURO CROSS 3.7L',
        '4D CUV 3.5L GLS',
        '4D SEDAN O-Z RALLY',
        'EXT CAB 3.0L SE',
        '4D SEDAN 2.5L',
        'EXT CAB 5.9L R/T',
        'EXT CAB 4.7L FFV ST',
        'CREW CAB 5.3L LS',
        'PASSENGER EXT 3.4L WARNER BROS',
        '2D CONVERTIBLE GT',
        '4D WAGON ZXW',
        'CREW CAB 4.0L LE',
        '4D SPORT UTILITY EX-P',
        '4D SUV LIMITED 2.4L',
        '4D SUV 5.7L HEMI',
        '4D SPORT UTILITY SR5',
        '2D EXT CAB 2.3L XL',
        'EXT CAB 3.9L SXT',
        'EXT CAB 4.3L SL',
        'REG CAB 4.0L XL',
        '4D SPORT UTILITY PREMIUM',
        '4D SEDAN SVT',
        '4D SEDAN ZX5',
        '4D SEDAN 6SP',
        '4D WAGON OUTBACK',
        '4D SPORT UTILITY LX AUTO',
        '4D UTILITY 5.3L LT',
        '4D UTILITY 5.3L FFV LT',
        '2D COUPE GT PREMIUM',
        'EXT CAB 4.2L XLT',
        '2D COUPE LXI',
        'REG CAB 5.4L XLT',
        '4D UTILITY 6.0L',
        'REG CAB 5.3L SLE',
        'EXT CAB 2.2L FFV',
        'REG CAB 5.7L HEMI',
        'REG CAB 2.2L FFV SL',
        'QUAD CAB 4.7L FFV',
        'REG CAB 4.0L EDGE',
        'QUAD CAB 4.7L LARAMIE',
        '4D SUV 2.4L LT',
        'QUAD CAB 5.7L LARAMIE',
        'min_valueIVAN 3.3L CARGO',
        'EXT CAB 4.3L SLE',
        'EXT CAB 5.4L KING RANCH',
        'min_valueIVAN 2.4L EC',
        '4D EXT CAB 4.0L EDGE',
        'WAGON 2.7L SE',
        '2D COUPE DX 5SP',
        '2D COUPE DX AUTO',
        '4D SEDAN 1LT',
        '4D SEDAN SE2',
        '4D SPORT UTILITY TOURING',
        '4D SUV-PICKUP 5.3L Z66',
        'EXT CAB 5.4L HERITAGE',
        'EXT CAB 3.4L SR5',
        '2D COUPE Z24',
        'CREW CAB 2.8L LS',
        '4D SEDAN EX 5SP',
        '4D SUV HARDTOP 2.2L LT',
        'QUAD CAB 5.9L',
        'EXT CAB 2.9L LS',
        'CREW CAB 4.0L SE',
        'CREW CAB 4.8L LS',
        '4D SPORT UTILITY OFF-ROAD',
        'min_valueIVAN 3.3L FFV SXT',
        '4D SEDAN TYPE S',
        'EXT CAB 3.4L PRERUNNER SR5',
        '2D LIFTBACK GT',
        'EXT CAB 5.4L FX4',
        '4D CUV 3.6L XE',
        '2D HATCHBACK S',
        'EXT CAB 5.4L FFV FX4',
        '4D SPORT UTILITY TOURING NAV',
        '2D CONVERTIBLE LIMITED',
        'QUAD CAB 4.7L BIG HORN',
        '4D SEDAN 2.5T',
        'REG CAB 3.9L SXT',
        '4D SUV 4.6L LIMITED',
        'min_valueIVAN 3.8L TOURING',
        'REG CAB 3.0L XL',
        'EXT CAB 5.3L LT Z71',
        '2D CONVERTIBLE SLE',
        'REG CAB 4.2L XLT',
        '4D SUV 4.0L PREMIER',
        '2D CONVERTIBLE GLS',
        '2D COUPE SE1',
        '4D HATCHBACK ZX5 SE',
        '4D SEDAN L AWD',
        'EXT CAB 2.4L LE',
        '4D WAGON OUTBACK SPORT',
        'REG CAB 4.6L W/T',
        '4D SEDAN 2.5I',
        'EXT CAB 2.4L SE',
        'REG CAB 5.7L',
        '2D EXT CAB 3.0L DUAL SPORT FFV',
        'EXT CAB 2.5L',
        'EXT CAB 5.6L SE',
        '4D min_valueIVAN EXT 3.4L GL',
        'PASSENGER EXT 3.4L LT',
        '4D SEDAN LS FFV',
        '4D SUV 5.3L FFV LT',
        '4D SUV 3.7L ST',
        '4D SEDAN SX',
        'EXT CAB 5.6L XE',
        '4D EXT CAB 3.0L XLT',
        '4D HATCHBACK ZX5 SES',
        '4D SEDAN XLE',
        'CREW CAB 3.5L SLE',
        '2D EXT CAB 3.0L XLT',
        '4D SUV 4.2L LTZ',
        '4D WAGON SX',
        'CREW CAB 5.4L FFV FX4',
        'EXT CAB 5.3L LT',
        'QUAD CAB 3.7L SXT',
        'CREW CAB 5.6L XE',
        'REG CAB 3.0L SPORT',
        '4D SUV SPORT 2.0L',
        '4D SUV 2.2L PANEL SS',
        '4D SEDAN SL',
        '4D SPORT UTILITY X',
        'QUAD CAB 4.7L SLT FFV',
        'EXT CAB 4.0L EDGE',
        'REG CAB 2.5L',
        'CREW CAB 6.0L SLT',
        'QUAD CAB 4.7L FFV LONESTAR',
        'CREW CAB 5.4L XLT',
        '2D COUPE TYPE S',
        '4D SUV 5.9L R/T',
        '4D SPORT UTILITY HYBRID LIMITED',
        '4D SEDAN OZ',
        '4D SUV 5.4L XLS',
        'CREW CAB 6.0L LT',
        'CREW CAB 4.7L LIMITED',
        '2D CONVERTIBLE LXI',
        '4D SEDAN PKG2',
        '2D HATCHBACK GT',
        'min_valueIVAN 3.3',
        '2D SPORT UTILITY',
        'PASSENGER EXT 3.4L ENTERTAINER',
        '4D SEDAN 2.5L GLS',
        '4D SEDAN NAVIGATION',
        'min_valueIVAN LX',
        'REG CAB 4.3L SL',
        '4D SEDAN 2.5 SE',
        '4D SEDAN AWD 3.5L',
        '2D COUPE ZX3 S',
        nan,
        'CREW CAB 6.0L',
        '5D min_valueIVAN LE',
        '4D SUV 3.7L SE',
        'JEEP X',
        '2D COUPE 5SP',
        'REG CAB 2.3L XLT',
        'WAGON 4D',
        '4D WAGON CLASSIC',
        '2D EXT CAB 3.0L SE',
        'EXT CAB 4.7L ST',
        'CREW CAB 2.8L',
        '4D SUV-PICKUP 8.1L',
        'EXT CAB 5.4L HARLEY DAVIDSON',
        'REG CAB 2.9L LS',
        'REG CAB 2.5L XLT',
        '4D WAGON SL',
        'REG CAB 2.3L XL',
        '4D CUV 2.2L XE',
        '2D EXT CAB 3.0L DUAL SPORT',
        'REG CAB 4.8L SL',
        '2D SUV CONVERTIBLE 2.0L',
        'EXT CAB 4.6L HERITAGE XL',
        '4D EXT CAB 4.0L FX4',
        'CREW CAB 4.6L KING RANCH',
        '2D SEDAN GX',
        'DOUBLE CAB LS 3.7L',
        '4D SEDAN LUXURY AWD',
        'EXT CAB 4.7L',
        'EXT CAB 4.6L LARIAT FX4 OFF-RD',
        '4D WAGON LUXURY',
        '4D WAGON 2.5I',
        '4D EXT CAB 4.0L XL',
        '2D EXT CAB 4.0L XL',
        '4D SEDAN TURBO',
        'CREW CAB 3.4L PRERUNNER',
        'EXT CAB 2.4L',
        'CREW CAB 3.3L',
        'ACCESS CAB 4.0L SR5',
        '4D SEDAN SPORT',
        '4D SEDAN VP 5SP',
        'REG CAB 5.4L W/T',
        '4D WAGON 2.4L',
        'CREW CAB 5.3L LT',
        'CARGO EXT 3.5L LT',
        '4D WAGON SE FFV',
        '4D SEDAN MAZDASPEED',
        'EXT CAB 3.0L XLT',
        '4D SEDAN TYPE S NAVIGATION',
        'REG CAB 5.4L FX4',
        '4D UTILITY DENALI 6.0L',
        'REG CAB 3.4L',
        'REG CAB 3.0L XLT',
        'EXT CAB 4.0L XLT',
        'EXT CAB 4.0L NISMO',
        'min_valueIVAN 3.8L LX',
        '4D WAGON LIMITED HEMI',
        '2D COUPE ZX5 S',
        'CREW CAB 3.5L',
        'CREW CAB 5.4L FX4',
        'REG CAB 4.8L SLE',
        'MEGA CAB 5.7L',
        'EXT CAB 6.0L SLE',
        'CREW CAB 3.3L SE',
        '2D COUPE DX VALUE PACKAGE AUTO',
        '4D SUV 4.7L FFV LIMITED',
        '4D WAGON L',
        'CREW CAB 5.4L FX2 SPORT',
        '4D WAGON SE COMFORT DURATEC',
        '4D SPORT UTILITY TOURING NAV DVD',
        '4D SPORT UTILITY BASE',
        'EXT CAB 4.6L XL',
        '4D SUV 5.3L FFV Z71',
        '2D CONVERTIBLE GL',
        '2D EXT CAB 4.0L EDGE',
        'EXT CAB 3.3L XE',
        '4D WAGON R/T AWD',
        '4D SEDAN XLS',
        '4D SEDAN LT CLASSIC',
        '4D SEDAN 3.5L SXT',
        '4D SEDAN CARTIER L',
        'EXT CAB LS 3.7L',
        '4D SEDAN T5',
        'PASSENGER 3.9L LIMITED',
        'REG CAB 6.0L LS',
        '4D UTILITY XUV 5.3L SLE',
        '4D SUV 4.0L CONVENIENCE',
        'EXT CAB LS SPECIAL 3.7L',
        '4D HARDTOP JLS',
        '4D SPORT UTILITY 4XMOTION',
        '4D EXT CAB 3.0L',
        'REG CAB 2.7L PRERUNNER SR5',
        'EXT CAB 3.9L BASE',
        'REG CAB 2.3L STX',
        'MEGA CAB 5.7L SLT',
        'REG CAB 2.7L',
        '4D SPORT UTILITY JS',
        'min_valueIVAN 3.3L LXI',
        'REG CAB 5.9L SLT',
        '4D CUV 2.0L XLT',
        '4D SEDAN 2.5L PKG 2',
        'REG CAB 4.7L ST',
        '4D SEDAN VALUE PACKAGE AUTO',
        '2D COUPE GTS',
        '4D CROSSOVER SE',
        'CREW CAB LIMITED',
        'CARGO 3.9L',
        'REG CAB 5.2L LARAMIE',
        '4D SPORT UTILITY SXT',
        'EXT CAB 3.9L SPORT',
        '4D CROSSOVER SEL PLUS',
        '4D SUV 5.9L SXT',
        '4D SUV 4.0L LIMITED',
        'CREW CAB 5.4L XL',
        '4D SEDAN ZX4 S',
        'REG CAB 3.9L SPORT',
        'JEEP SPORT',
        '4D WAGON FREEDOM',
        '4D SUV 4.7L SLT PLUS',
        '4D SEDAN 3.5L AWD SXT',
        '4D SEDAN 2.0L GLS',
        '4D SUV HARDTOP 2.2L ZR2',
        'WAGON SXT AWD',
        '4D SUV 4.8L LT',
        '4D WAGON 1.8L',
        'REG CAB 2.8L LS',
        '4D WAGON SEL',
        '4D SUV 6.2L LUXURY',
        '2D COUPE LTZ',
        '4D UTILITY 5.3L FFV Z71',
        '4D WAGON CXL',
        '4D SPORT UTILITY GRAND TOURING A',
        'REG CAB 3.7L SLT',
        'REG CAB 4.3L W/T',
        '4D WAGON LL BEAN',
        'SPORT UTILITY 7 PASSENGER',
        '4D SEDAN 2.5RS',
        '2D EXT CAB 3.0L XL',
        '3D EXT CAB 2.2L FFV',
        '2D SUV 4.0L SPORT XLT',
        'MAZDA3 4D I TOURING VALUE',
        '4D SPORT WAGON 2.5I',
        '4D SEDAN HYBRID AUTO',
        'DOUBLE CAB LS SPECIAL 3.7L',
        '4D SUV 5.3L XLT',
        '4D WAGON ROCKY MOUNTAIN EDITION',
        '4D SUV 2.5L PREMIER',
        '4D SUV 2.2L PANEL LS',
        '4D SPORT UTILITY LUXURY',
        'EXT CAB DURO CROSS 3.7L',
        'PASSENGER 3.4L LS',
        '4D SEDAN SIGNATURE LTD',
        'CREW CAB 3.5L Z71 LS',
        '4D SUV 2.4L LUXURY',
        '2D EXT CAB 2.3L EDGE',
        '4D EXT CAB 3.0L XL',
        '4D SEDAN 2.7L SXT',
        '4D SPORT UTILITY JLX',
        '4D SUV 6.0L LS',
        '5D min_valueIVAN CE',
        'EXT CAB 4D 5.2L LARAMIE SLT',
        '4D SEDAN 2.0L GL',
        'MAZDA3 4D I',
        '2D COUPE TYPE S NAVIGATION AUTO',
        '4D SUV 4.0L LUXURY',
        '2D ROADSTER GXP',
        '4D SPORT UTILITY SE SUPERCHARGED',
        '4D SUV 4.0L SPORT TRAC FFV XLS',
        'min_valueIVAN EX',
        '4D EXT CAB 4.0L XLT',
        'EXT CAB 4.3L W/T',
        'CREW CAB 2.9L LT',
        'EXT CAB 4D 5.9L LARAMIE SLT',
        'EXT CAB 3.5L SLE',
        '4D SUV 5.9L SLT PLUS',
        'EXT CAB 3.7L ST',
        'REG CAB 3.7L LS',
        'CREW CAB 5.7L LIMITED',
        '4D SUV 5.9L SPORT',
        '2D COUPE ZX3 SES',
        'REG CAB 3.5L Z71',
        '5D SEDAN S GRAND TOURING',
        '4D SEDAN 35TH ANNIVERSARY AWD',
        'REG CAB 3.7L STAMPEDE',
        'EXT CAB 4.0L SE',
        'min_valueIVAN 3.3L FFV EL'])
            topthreeamericanname=  st.selectbox('Identifies if the manufacturer is one of the top three American manufacturers',['OTHER', 'CHRYSLER', 'FORD', 'GM'])
            transmission=  st.selectbox('Vehicles transmission type (Automatic, Manual)',['AUTO', 'MANUAL','Manual'])
            trim=  st.selectbox('Vehicle Trim Level',['i',
        'ST',
        'SXT',
        'ZX3',
        'ES',
        'EX',
        'SE',
        'SEL',
        'SLE',
        'XL',
        'Bas',
        'LS',
        nan,
        'SS',
        'SLT',
        '150',
        'Spo',
        'LX',
        'GLS',
        'CE',
        'GT',
        'Lar',
        '2',
        'Adv',
        'SR5',
        'GXP',
        'Tou',
        'XLT',
        'LT',
        'SES',
        'XLS',
        'GL',
        'LE',
        '1',
        'L20',
        'Lim',
        's',
        'Edd',
        '3',
        'Edg',
        'ZTW',
        'ZX4',
        'STX',
        'CX',
        'Nor',
        'GS',
        'XE',
        'CXL',
        'Ren',
        'LTZ',
        'ZTS',
        'S',
        'GTC',
        'GTP',
        'Cla',
        'Spy',
        'LXi',
        'SE-',
        'Exe',
        'Pre',
        'SL2',
        'GXE',
        'SL1',
        'Cus',
        'GLE',
        'DE',
        'Z71',
        'Si',
        'X',
        'SX',
        'XR',
        'SVT',
        'GTS',
        'LW3',
        'SV6',
        'Val',
        'Car',
        'eL',
        'DX',
        'Spe',
        'W/T',
        'LW2',
        'Pro',
        'SL',
        'L30',
        'RT',
        'CXS',
        'VP',
        'Cin',
        'max_value',
        'Ral',
        'Sta',
        'Lux',
        'R/T',
        'Her',
        'ZX5',
        'Xsp',
        'Kin',
        '3 R',
        'Hig',
        'GX',
        'EX-',
        'RS',
        'Plu',
        'Ult',
        'DS',
        'Ove',
        'Den',
        'XRS',
        'SC2',
        'Sig',
        'SC1',
        'XS',
        'C',
        'ZX2',
        'ZXW',
        'ZR2',
        'Dur',
        'OZ',
        'L',
        '250',
        'eC',
        'FX4',
        'Out',
        'L10',
        'Maz',
        'Ent',
        'T5',
        'Z24',
        'Har',
        'LL',
        'Hyb',
        'JLX',
        'JLS',
        'L 3'])
            vnst=  st.selectbox('State where the the car was purchased',['FL',
        'VA',
        'IA',
        'AR',
        'MN',
        'TN',
        'PA',
        'OH',
        'AL',
        'MI',
        'TX',
        'IL',
        'MA',
        'AZ',
        'GA',
        'NC',
        'MD',
        'CA',
        'UT',
        'OR',
        'SC',
        'CO',
        'ID',
        'NV',
        'WV',
        'MS',
        'OK',
        'NM',
        'LA',
        'IN',
        'MO',
        'WA',
        'NH',
        'NJ',
        'NY',
        'NE',
        'KY'])
            vnzip1 =  st.selectbox('Zipcode where the car was purchased',[33619,
        20166,
        50111,
        72117,
        55369,
        38118,
        17406,
        16137,
        34203,
        45005,
        35004,
        48265,
        75061,
        78610,
        60440,
        60445,
        2764,
        77301,
        85040,
        30272,
        37138,
        27542,
        21075,
        94544,
        21014,
        77041,
        79605,
        84104,
        95673,
        97060,
        75020,
        92807,
        29697,
        32824,
        29461,
        76101,
        37421,
        80022,
        43207,
        85018,
        75236,
        76040,
        83716,
        97402,
        89506,
        85248,
        16066,
        29532,
        25177,
        32124,
        76063,
        35613,
        38637,
        80229,
        75050,
        73108,
        85009,
        80011,
        74135,
        79932,
        85284,
        32812,
        89139,
        27407,
        91763,
        78745,
        80112,
        32225,
        87109,
        70002,
        77073,
        25071,
        45011,
        38128,
        32750,
        34761,
        90045,
        22403,
        46803,
        30331,
        30529,
        60443,
        89120,
        89165,
        70460,
        85353,
        22801,
        19440,
        64161,
        99224,
        64153,
        17028,
        91770,
        33809,
        33314,
        85260,
        70401,
        47129,
        17545,
        30315,
        83687,
        87105,
        32503,
        78219,
        29323,
        3106,
        39402,
        26431,
        37122,
        8505,
        12552,
        92101,
        85338,
        90650,
        73129,
        68138,
        85204,
        97217,
        33073,
        23606,
        30120,
        42104,
        29070,
        39208,
        23234,
        92504,
        92057,
        46239,
        62207,
        71119,
        77086,
        78754,
        32772,
        33311,
        98064,
        92337,
        37771,
        91752,
        33916,
        78426,
        33762,
        63044,
        28625,
        85226,
        37210,
        28273,
        77061,
        84087,
        33411,
        80817,
        32219,
        78227,
        30212])
            vehbcost=  st.number_input('Acquisition cost paid for the vehicle at time of purchase',min_value=1.0,max_value=50000.0)
            vehodo=  st.number_input('The vehicles odometer reading',min_value=4500,max_value=116000)
            vehyear=  st.number_input('The manufacturer\'s year of the vehicle',min_value=2001,max_value=2010)
            vehicleage=  st.number_input('The Years elapsed since the manufacturer\'s year',min_value=0,max_value=9)
            warrantycost=  st.number_input(' Warranty price (term=36month  and millage=36K) ',min_value=400,max_value=7500)
            wheeltype=  st.selectbox('The vehicle wheel type description (Alloy, Covers)',['Alloy', 'Covers', 'Special'])
            wheeltypeid=  st.selectbox('The type id of the vehicle wheel',[1.0,2.0,3.0])
            mmracquisitionauctionaverageprice = st.number_input('Acquisition price for this vehicle in average condition at time of purchase	',min_value=0.0,max_value=8000.0)
            mmracquisitionauctioncleanprice= st.number_input('Acquisition price for this vehicle in the above Average condition at time of purchase',min_value=0.0,max_value=8000.0)
            mmracquisitionretailaverageprice= st.number_input('Acquisition price for this vehicle in the retail market in average condition at time of purchase',min_value=0.0,max_value=8000.0)
            mmracquisitonretailcleanprice= st.number_input('Acquisition price for this vehicle in the retail market in above average condition at time of purchase',min_value=0.0,max_value=8000.0)
            mmrcurrentauctionaverageprice= st.number_input('Acquisition price for this vehicle in average condition as of current day	',min_value=0.0,max_value=8000.0)
            mmrcurrentauctioncleanprice= st.number_input('Acquisition price for this vehicle in the above condition as of current day',min_value=0.0,max_value=8000.0)
            mmrcurrentretailaverageprice= st.number_input('Acquisition price for this vehicle in the retail market in average condition as of current day',min_value=0.0,max_value=8000.0)
            mmrcurrentretailcleanprice= st.number_input('Acquisition price for this vehicle in the retail market in above average condition as of current day',min_value=0.0,max_value=8000.0)

            output = ''

            input ={
        'AUCGUART':aucguart,
        'Auction':auction ,
        'BYRNO':byrno,
        'Color':color ,
        'IsOnlineSale':onlinesale ,
        'Make':model ,
        'Model':nationality ,
        'Nationality':primeunit ,
        'PRIMEUNIT':purchdate ,
        'PurchDate':refid ,
        'Size':size ,
        'SubModel':submodel ,
        'TopThreeAmericanName':topthreeamericanname ,
        'Transmission':transmission ,
        'Trim':trim ,
        'VNST':vnst ,
        'VNZIP1':vnzip1 ,
        'VehBCost':vehbcost ,
        'VehOdo':vehodo ,
        'VehYear':vehyear ,
        'VehicleAge':vehicleage ,
        'WarrantyCost':warrantycost ,
        'WheelType':wheeltype ,
        'WheelTypeID':wheeltypeid ,
        'MMRAcquisitionAuctionAveragePrice':mmracquisitionauctionaverageprice ,
        'MMRAcquisitionAuctionCleanPrice':mmracquisitionauctioncleanprice ,
        'MMRAcquisitionRetailAveragePrice':mmracquisitionretailaverageprice ,
        'MMRAcquisitonRetailCleanPrice':mmracquisitonretailcleanprice ,
        'MMRCurrentAuctionAveragePrice':mmrcurrentauctionaverageprice ,
        'MMRCurrentAuctionCleanPrice':mmrcurrentauctioncleanprice ,
        'MMRCurrentRetailAveragePrice':mmrcurrentretailaverageprice ,
        'MMRCurrentRetailCleanPrice':mmrcurrentretailcleanprice ,
    }

            
            if st.button('Predict Online'):
                output = 'Good' if predict_input(rf_model,[input]) else 'Bad'
                st.success(f'Your car is a {output} buy !')

        elif add_selectbox == 'Batch':
            file_upload = st.file_uploader("Upload csv file for predictions", type=["csv"])
            if file_upload is not None:
                data = pd.read_csv(file_upload)
                output = predict_input(rf_model,data)   

            if st.button('Predict Batch'):
                for value, id in zip(output, data.RefId):
                    value = 'Good' if value else 'Bad'
                    st.success(f'Your car for RefID {id} is a {value} buy !')
        
    except Exception as e:
        st.warning('Please provide proper inputs in order to generate prediction(s)!')  
        st.warning(e)


if __name__ == '__main__':
    main()